---
language: python
python: "3.7"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  matrix:
    - MOLECULE_DISTRO: jessie
    - MOLECULE_DISTRO: stretch
    - MOLECULE_DISTRO: buster
script:
  - export MOLECULE_DISTRO=${MOLECULE_DISTRO}
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
