---
- name: NGINX | Configuring user groups
  user:
    name: "{{ nginx_user }}"
    groups: "{{ nginx_groups|join(',') }}"
    append: yes

- name: NGINX | Update conf directory owner
  file:
    name: "{{ nginx_conf_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: NGINX | Copy server config
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0640"
  notify: restart nginx
  with_items:
    - "etc/nginx/nginx.conf"

- name: NGINX | Copy logrotate config
  copy:
    src: logrotate
    dest: /etc/logrotate.d/nginx

- name: NGINX | Create servers directory
  file:
    path: "{{ nginx_conf_dir }}{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  with_items:
    - sites-available
    - sites-enabled

- name: NGINX | Copy Daemon script
  copy:
    src: nginx.service
    dest: /lib/systemd/system/
    mode: 0755
  notify: restart nginx
