---
- name: NGINX | Configuring user groups
  user:
    name: "{{ nginx_user }}"
    groups: "{{ nginx_groups|join(',') }}"
    append: yes

- name: NGINX | Create pid directory
  file:
    path: "{{ nginx_pid_path }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    recurse: yes

- name: NGINX | Create log directory
  file:
    path: "{{ nginx_log_path }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    recurse: yes

- name: NGINX | Update conf directory owner
  file:
    name: "{{ nginx_conf_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: NGINX | Copy server config
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0640"
  notify: restart nginx
  with_items:
    - "etc/nginx/nginx.conf"

- name: NGINX | Create servers directory
  file:
    path: "{{ nginx_conf_path }}{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  with_items:
    - sites-available
    - sites-enabled

- name: NGINX | Copy logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/nginx
    mode: 0644
    owner: root
    group: root
