---

- name: NGINX | Installing lua dependencies
  apt:
    pkg: "{{ lua_required_libs }}"
    state: present
  loop: "{{ lua_required_libs }}"

- name: NGINX | Check lua version
  command: lua -v
  register: lua_check
  changed_when: false
  ignore_errors: true

- name: NGINX | Download lua
  unarchive:
    copy: false
    src: "{{ lua_url }}"
    dest: /tmp
  when: nginx_force_reinstall or
        lua_check is failed or
        "Lua " + lua_version not in lua_check.stderr

- name: NGINX | Build lua
  make:
    chdir: "/tmp/lua-{{ lua_version }}"
    target: "{{ item }}"
  loop:
    - linux
    - install
  when: nginx_force_reinstall or
        lua_check is failed or
        "Lua " + lua_version not in lua_check.stderr
