---

- name: NGINX | Installing lua dependencies
  apt:
    pkg: "{{ luajit_required_libs }}"
    state: present
  loop: "{{ luajit_required_libs }}"

- name: NGINX | Check luaJIT version
  command: luajit -v
  register: luaJIT_check
  changed_when: false
  ignore_errors: true

- name: NGINX | Download luaJIT
  unarchive:
    copy: false
    src: "{{ luaJIT_url }}"
    dest: "{{ nginx_download_dir }}"
  when: nginx_force_reinstall or
        luaJIT_check is failed or
        "LuaJIT " + luaJIT_version[:3] not in luaJIT_check.stdout

- name: NGINX | Build luaJIT
  make:
    chdir: "{{ nginx_download_dir }}/luajit2-{{ luaJIT_version }}"
    target: install
  when: nginx_force_reinstall or
        luaJIT_check is failed or
        "LuaJIT " + luaJIT_version[:3] not in luaJIT_check.stdout
