---

- name: NGINX | Installing dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ required_libs }}"
  tags:
    skip_ansible_lint

- name: NGINX | Check nginx version
  command: nginx -v
  register: nginx_check
  changed_when: false
  ignore_errors: true

- name: NGINX | Download headers-more module
  get_url:
    url: "{{ headers_more_url }}"
    dest: /tmp
    validate_certs: no
  when: 'nginx_force_reinstall or nginx_check|failed or "nginx/{{ nginx_version }}" not in nginx_check.stderr'

- name: NGINX | Untar headers-more
  unarchive:
    copy: no
    src: /tmp/headers-more-nginx-module-{{ headers_more_version }}.tar.gz
    dest: /tmp
  when: 'nginx_force_reinstall or nginx_check|failed or "nginx/{{ nginx_version }}" not in nginx_check.stderr'

- name: NGINX | Download lua module
  get_url:
    url: "{{ lua_module_url }}"
    dest: /tmp
    validate_certs: no
  when: 'nginx_force_reinstall or nginx_check|failed or "nginx/{{ nginx_version }}" not in nginx_check.stderr'

- name: NGINX | Untar lua module
  unarchive:
    copy: no
    src: /tmp/lua-nginx-module-{{ lua_module_version }}.tar.gz
    dest: /tmp
  when: 'nginx_force_reinstall or nginx_check|failed or "nginx/{{ nginx_version }}" not in nginx_check.stderr'

- name: NGINX | Download nginx
  get_url:
    url: "{{ nginx_url }}"
    dest: /tmp
  when: 'nginx_force_reinstall or nginx_check|failed or "nginx/{{ nginx_version }}" not in nginx_check.stderr'

- name: NGINX | Untar nginx
  unarchive:
    copy: no
    src: /tmp/nginx-{{ nginx_version }}.tar.gz
    dest: /tmp
  when: 'nginx_force_reinstall or nginx_check|failed or "nginx/{{ nginx_version }}" not in nginx_check.stderr'

- name: NGINX | Install nginx
  command: "chdir=/tmp/nginx-{{ nginx_version }} {{item}}"
  with_items:
    - ./configure
        --prefix={{ nginx_install_bin_path }}
        --user={{ nginx_user }}
        --group={{ nginx_group }}
        --with-http_stub_status_module
        --add-module=/tmp/headers-more-nginx-module-{{ headers_more_version }}
        --add-module=/tmp/lua-nginx-module-{{ lua_module_version }}
        --conf-path={{ nginx_conf }}
        --error-log-path={{ nginx_error_log }}
        --http-log-path={{ nginx_access_log }}
        --pid-path={{ nginx_pid_path }}nginx.pid
        --lock-path=/var/lock/nginx.lock
    - make
    - make install
  when: 'nginx_force_reinstall or nginx_check|failed or "nginx/{{ nginx_version }}" not in nginx_check.stderr'
  notify: restart nginx

- name: NGINX | Copy Daemon script
  template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service
    mode: 0644
  notify: restart nginx
