---
- name: NGINX | Get nginx-lua-prometheus
  unarchive:
    src: "{{ nginx_lua_prometheus_url }}"
    dest: "{{ nginx_download_dir }}"
    remote_src: true

- name: NGINX | Copy prometheus lib
  copy:
    src: "{{ nginx_download_dir }}/nginx-lua-prometheus-{{ nginx_lua_prometheus_version }}/{{ item }}"
    dest: "{{ nginx_conf_path }}/plugins/{{ item }}"
    remote_src: true
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  loop: "{{ nginx_lua_scripts }}"

- name: NGINX | Get prometheus lua external dependencies
  unarchive:
    copy: false
    src: "{{ item.url }}"
    dest: "{{ nginx_conf_path }}/plugins"
  loop: "{{ nginx_lua_external_dependencies }}"

- name: NGINX | Copy prometheus metric server conf
  template:
    src: metrics/prometheus.j2
    dest: "{{ nginx_conf_path }}/sites-available/prometheus"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: NGINX | Copy prometheus server config
  template:
    src: metrics/prometheus.conf.j2
    dest: "{{ nginx_extra_conf_path }}/prometheus.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0640"

- name: NGINX | Enable prometheus metric server
  file:
    src: "{{ nginx_conf_path }}/sites-available/prometheus"
    dest: "{{ nginx_conf_path }}/sites-enabled/prometheus"
    state: link
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify: restart nginx
