---

- name: NGINX | Copy prometheus lib
  copy:
    src: prometheus.lua
    dest: "{{ nginx_conf_path }}/plugins/prometheus.lua"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
#  when: 'prometheus_metric_enabled'

- name: NGINX | Copy prometheus metric server conf
  template:
    src: prometheus.j2
    dest: "{{ nginx_conf_path }}/sites-available/prometheus"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
#  when: 'prometheus_metric_enabled'

- name: NGINX | Enable prometheus metric server
  file:
    src: "{{ nginx_conf_path }}/sites-available/prometheus"
    dest: "{{ nginx_conf_path }}/sites-enabled/prometheus"
    state: link
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
#  when: 'prometheus_metric_enabled'
  notify: reload nginx

