---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: nginx-${MOLECULE_DISTRO:-buster}-slim
    image: debian:${MOLECULE_DISTRO:-buster}-slim
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - nginx
    tmpfs:
      - '/run'
      - '/run/lock'
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: ansible
